cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include("hw.urls")),
    path('quotes/', include("quotes.urls")),
    path('formdata/', include("formdata.urls")),
    path('restaurant/', include("restaurant.urls")),
    path('blog/', include("blog.urls")),
    path('mini_fb/', include("mini_fb.urls")),
    path('marathon_analytics/', include("marathon_analytics.urls")),
    path('voter_analytics/', include("voter_analytics.urls")),
    path('project/', include("project.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hw/urls.py
## hw/urls.py

from django.urls import path
from django.conf import settings
from . import views

#list of urls to have
urlpatterns = [
    path(r'', views.home, name="home"),#name is same as the name of views
    path(r'about', views.about, name="about"),
    #must have the r before ''
    #path(url, view, name)
    
]

project/urls.py
# File: urls.py
# Author: Shuaiqi Huang (shuang20@bu.edu) 12/08/2024
# Description: url patterns for different pages

from django.urls import path
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_views

app_name='project'

urlpatterns = [
    path('', views.ShowAllItemView.as_view(), name='show_all'), #base view
    path('item/<int:pk>/', views.ShowDetailItemView.as_view(), name='show_detail'), #details of each item and some info about seller
    path('user/<int:pk>/', views.ShowUserPageView.as_view(), name="show_user"), #user profile view, can be accessed even if user did not login
    path('user/', views.ShowUserSelfView.as_view(), name="show_self"), #user self view, only available to the user itself and cannot be accessed by other, since this allows update of account info and selling/updating/deleting an item 
    path('logout/', auth_views.LogoutView.as_view(template_name='project/logout.html'), name='logout'), #logout view for every user
    path('cart/', views.ShowCartView.as_view(), name='shopping_cart'), #shopping cart of the user, contains items that user has added, allows update/delete
    path('create_user/', views.CreateCustomerView.as_view(), name='create_customer'), #used when registration of a new user
    path('add_to_cart/<int:item_pk>/add/', views.AddToCartView.as_view(), name='add_to_cart'), #adding an item to the shopping cart of the user
    path('login/', views.CustomLoginView.as_view(), name='login'), #login page for every user, asking for correct username and password combination
    path('customer/update/', views.UpdateCustomerView.as_view(), name='update_account'), #updating account info, can be accessed in ShowUserSelfView as a button
    path('add_follower/<int:customer_pk>/', views.AddFollowerView.as_view(), name='add_follower'), #enable following of one user to the aother, which creates a Follower object
    path('followings/', views.FollowingsListView.as_view(), name='following_list'), #check who the user is following, shown as a ist
    path('followers/', views.FollowersListView.as_view(), name='follower_list'), #check who is the follower of the user, shown as a list
    path('chats/', views.ChatListView.as_view(), name='chat_list'), #see who the user has sent message or someone has sent the message to the user, and contains chat history
    path('chats/<int:customer_pk>/', views.ChatDetailView.as_view(), name='chat_detail'), #chat page between 2 users, can be accessed from the ChatListView
    path('item/create/', views.CreateItemView.as_view(), name='create_item'), #creating a new item to sell, to be accessed in ShowUserSelfView(you have to be the user to sell an item)
    path('item/update/<int:pk>/', views.UpdateItemView.as_view(), name='update_item'), #updating an item, can be accessed in ShowUserSelfView for each user's item
    path('cart/checkout/', views.CheckoutCartView.as_view(), name='checkout_cart'), #checkout for the cart, user can select item to checkout
    path('notifications/', views.NotificationListView.as_view(), name='notification'), #list of notification, which notifies the seller who bought an item
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'), #order detail from notification, for each notification, we can see the detail of the order
    path('pastorder/', views.PastOrdersView.as_view(), name='past_order'), # list of orders for each user has placed
    path('notifications/mark_as_read/<int:pk>/', views.MarkNotificationReadView.as_view(), name='mark_notification_read'),#mark the notification as read, so the red dot on Notifications link  dissappears
    path('item/<int:pk>/delete/', views.DeleteItemView.as_view(), name='delete_item'), #deleting an item for the user, in other words, stop selling it
    path('graphs', views.StatisticsView.as_view(), name='graph'), #graphs for the web application
   ]

project/views.py
# File: views.py
# Author: Shuaiqi Huang (shuang20@bu.edu) 12/08/2024
# Description: all views that the web applictaion use, including login/logout of user
# also includes form that applications that will be used

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import *
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, TemplateView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import *
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import redirect
from django.utils.timezone import timedelta
from datetime import date
from django.db.models import Count
from django.utils.dateparse import parse_date
import plotly
import plotly.graph_objs as go
from plotly.offline import plot


class ShowAllItemView(ListView):
    '''shows all the item, which is the homepage, and allows filtering based on criteria
    to avoid too many item being dispaged, add a paginate_by field to limit the number of items shown'''
    model = Item
    template_name = 'project/show_all_items.html'
    context_object_name = 'items'
    paginate_by = 10

    def get_queryset(self):
        '''once search form is submitted, filter out the unmatching criteria'''
        queryset = super().get_queryset()

        # Get filter and sort parameters
        search_title = self.request.GET.get('search_title', '')
        sort_by = self.request.GET.get('sort_by', '')
        print(search_title,sort_by)

        # Apply filters
        if search_title:
            queryset = queryset.filter(title__icontains=search_title)

        # Exclude soft-deleted items
        queryset = queryset.filter(is_deleted=False)

        # Apply sorting
        if sort_by == 'price_asc':
            queryset = queryset.order_by('price')  # Cheapest first
        elif sort_by == 'price_desc':
            queryset = queryset.order_by('-price')  # Expensive first
        elif sort_by == 'date_asc':
            queryset = queryset.order_by('date')  # Oldest first
        elif sort_by == 'date_desc':
            queryset = queryset.order_by('-date')  # Newest first

        return queryset



class ShowDetailItemView(DetailView):
    '''Detail of an item, can be accessed many ways, one of the way is by hitting the item
    in the ShowItemsView'''
    model = Item
    template_name = 'project/item_detail.html'
    context_object_name = 'item'


class ShowUserPageView(DetailView):
    '''show a specific account from the databse, this is the version that doesnt require any logins
    this does not include updating account info, and selling new items, etc.'''
    model = Customer
    template_name = 'project/customer_detail.html'
    context_object_name = 'customer'

    def get_context_data(self, **kwargs):
        '''showuserpageview versin of get_context_data'''
        context = super().get_context_data(**kwargs)

        # Check if the logged-in user is following the current customer
        customer = context['customer']
        is_following = False
        if self.request.user.is_authenticated:
            is_following = self.request.user.customer.is_following(customer)

        items = customer.items.filter(is_deleted=False) 
        context['items'] = items

        # Add the 'is_following' status to the context
        context['is_following'] = is_following
        return context

class ShowUserSelfView(LoginRequiredMixin, DetailView):
    '''show a specific account from the database, this version requires login, which allows
    update of info, selling an item, updating an existing item. Additionally, the user who is not
    associated with this account cannot access this page, but only the ShowUserPageView(previous view)'''
    model = Customer
    template_name = 'project/show_user.html'
    context_object_name = 'customer'

    def get_object(self, queryset=None):
        # Retrieve the Customer object for the logged-in user
        return get_object_or_404(Customer, user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Filter out soft-deleted items so that it does not get shown
        customer = self.get_object()
        items = customer.items.filter(is_deleted=False)
        context['items'] = items
        return context

class UpdateCustomerView(LoginRequiredMixin, UpdateView):
    '''update an existing customer, and have to be the correct user to make such update, updates
    are performed using the form in forms.py'''
    model = Customer
    template_name = 'project/update_customer_form.html'
    form_class = UpdateCustomerForm

    def get_success_url(self):
        # Redirect to the ShowUserSelfView after a successful update
        return reverse('project:show_self')
    
    def get_object(self, queryset=None):
        #get profile of self
        return Customer.objects.get(user=self.request.user)

class ShowCartView(LoginRequiredMixin, TemplateView):
    '''showing the shopping cart of the user, the user can only access the shopping cart that associated
    with them, and has no access to other people's shopping cart, shopping cart allows CRUD on item'''
    model = ShoppingCart
    template_name = 'project/shopping_cart.html'
    context_object_name = 'cart'


    def post(self, request, *args, **kwargs):
        '''once a submit of form is observed, do corresponding action'''
        # Get the shopping cart associated with the logged-in user
        cart = ShoppingCart.objects.get(user=request.user)
        action = request.POST.get('action')  # Action to be performed

        if action == 'update':
            # Update quantities for each item in the cart
            for cart_item in cart.cart_items.all():
                quantity_key = f'quantity_{cart_item.id}'
                if quantity_key in request.POST:
                    try:
                        new_quantity = int(request.POST[quantity_key])
                        # Ensure the new quantity is valid and does not exceed stock
                        if new_quantity > 0 and new_quantity <= cart_item.item.quantity_left:
                            cart_item.quantity = new_quantity
                            cart_item.save()
                        else:
                            # Handle invalid quantity (e.g., too high or zero)
                            cart_item.quantity = cart_item.quantity  # Retain original value
                            cart_item.save()
                    except ValueError:
                        # Handle invalid quantity (e.g., non-integer input)
                        continue
            return redirect('project:shopping_cart') #redirect after update completes

        elif action == 'delete':
            # Delete selected items from the cart
            delete_items = request.POST.getlist('delete_items')
            if delete_items:
                cart.cart_items.filter(id__in=delete_items).delete()
            return redirect('project:shopping_cart') #redirect after delete completes

        elif action == 'submit_order':
            # Process the order and create a new order object
            # Ensure cart has items before submitting the order
            cart = request.user.shopping_cart
        cart_items = cart.cart_items.all()

        # Get the list of selected items' IDs from the checkbox
        selected_item_ids = request.POST.getlist('delete_items')

        if not selected_item_ids:
            return redirect('project:shopping_cart')

        selected_item_ids = [int(item_id) for item_id in selected_item_ids]

        # Create a grouped CustomerOrder for the customer
        customer_order = CustomerOrder.objects.create(customer=request.user.customer)

        for cart_item in cart_items:
            if cart_item.pk in selected_item_ids:
                if cart_item.quantity > cart_item.item.quantity_left:
                    cart_item.delete()  # Remove item if stock is insufficient
                    continue

                # Create an individual order for each item
                order = Order.objects.create(
                    customer_order=customer_order,
                    customer=request.user.customer,
                    item=cart_item.item,
                    quantity=cart_item.quantity,
                    seller=cart_item.item.customer,
                )

                # Notify the seller by creating a Notification object
                Notification.objects.create(
                    user=cart_item.item.customer.user,
                    message=(
                        f"You have received an order for {cart_item.item.title} "
                        f"(Quantity: {cart_item.quantity}). "
                        f"Total Price: ${cart_item.get_total_price()}"
                    ),
                    order=order,
                )

                # Reduce stock of the item
                cart_item.item.quantity_left -= cart_item.quantity
                cart_item.item.save()

                # Remove the item from the cart
                cart_item.delete()

                return redirect('project:checkout_cart')  # Redirect to order confirmation page

            else:
                # If cart is empty, you can add a message or redirect back
                return redirect('project:shopping_cart')  # Redirect to shopping cart if no items are selected

        # Default return for other actions or invalid requests
        return redirect('project:shopping_cart')  # Redirect back to the shopping cart



    def get_context_data(self, **kwargs):

project/templates/project/base.html
<!-- same file name as the views name 
 base page from which all other pages will inherit-->


 {% load static %}

 <html>
     <head>
         <link rel = "stylesheet" href = "{% static 'styles_project.css' %}"> 
         <title>
            Shopping now
         </title>
     </head>
 
 
     <body>
         
        <nav style="display: flex; justify-content: space-between; align-items: flex-start; padding: 10px;">
            <!-- Left side -->
            <div style="display: flex; flex-direction: column; align-items: flex-start;">
                <a href="{% url 'project:show_all' %}" style="text-decoration: none; margin-bottom: 10px;">Home</a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'project:following_list' %}" style="text-decoration: none; margin-bottom: 10px;">My Following</a>
                <a href="{% url 'project:follower_list' %}" style="text-decoration: none; margin-bottom: 10px;">My Follower</a>
                <a href="{% url 'project:notification' %}" style="text-decoration: none; margin-bottom: 10px; position: relative;">
                    Notifications
                    {% if has_unread %}
                        <span style="position: absolute; top: -5px; right: -10px; width: 10px; height: 10px; background-color: red; border-radius: 50%;"></span>
                    {% endif %}
                </a>
                <a href="{% url 'project:graph' %}" style="text-decoration: none; margin-bottom: 10px;">Statistics</a>

                <p style="margin-bottom: 10px; margin-left: 10px;">
                    Logged in: {{ request.user }}
                </p>
                {% endif %}
            </div>

            
            <!-- Right side -->
            <div style="text-align: right;">
                {% if request.user.is_authenticated %}
                    <form method="POST" action="{% url 'project:logout' %}" style="display: inline;">
                        {% csrf_token %}
                        <a href="#" onclick="this.closest('form').submit();" 
                           style="text-decoration: none; display: block; margin-bottom: 10px;">
                            Logout
                        </a>
                    </form>
                    <a href="{% url 'project:show_self' %}" style="display: block; margin-bottom: 10px; text-decoration: none;">
                        Account Info
                        {% if has_unread %}
                            <span class="red-dot"></span>
                        {% endif %}
                    </a>
                    
                    <a href="{% url 'project:shopping_cart' %}" style="display: block; margin-bottom: 10px; text-decoration: none;">
                        Shopping Cart
                    </a>
                    <a href="{% url 'project:chat_list' %}" style="display: block; margin-bottom: 10px; text-decoration: none;">
                        Messages
                    </a>
                    <a href="{% url 'project:past_order' %}" style="display: block; margin-bottom: 10px; text-decoration: none;">
                        Past Orders
                    </a>
                    
                {% else %}
                    <a href="{% url 'project:login' %}" style="display: block; margin-bottom: 10px; text-decoration: none;">
                        Login
                    </a>
                    <a href="{% url 'project:create_customer' %}" style="display: block; margin-bottom: 10px; text-decoration: none;">
                        Register
                    </a>
                {% endif %}
            </div>
        </nav>
        

        {% block content %}
        <!-- put stuff/content here-->
        {% endblock %}
     </body>
 </html>

project/templates/project/cart_confirm_delete.html
{% extends 'project/base.html' %}

{% block content %}
<h1>Confirm Delete</h1>
<p>Are you sure you want to remove "{{ object.item.title }}" from your cart?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'project:shopping_cart' %}">Cancel</a>
</form>
{% endblock %}

project/templates/project/chat_detail.html
{% extends "project/base.html" %}
{% block content %}
    

<div class="chat-wrapper">
    <h2>
        Chat with {{ other_customer.first_name }} {{ other_customer.last_name }}
    </h2>
    

    <div class="chat-container">
        {% for message in messages %}
            <div class="message {% if message.sender == request.user.customer %}sent{% else %}received{% endif %}">
                <p>{{ message.message }}</p>
                {% if message.image_self %}
                    <img src="{{ message.image_self.url }}" alt="Message Image">
                {% endif %}
                <div class="timestamp">{{ message.date }}</div>
            </div>
        {% empty %}
            <p>No messages yet.</p>
        {% endfor %}
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
</div>
{% endblock %}

project/templates/project/checkout_cart.html
{% extends 'project/base.html' %}

{% block content %}
<h1>Checkout Successful</h1>
<p>Your order has been successfully placed!</p>
<a href="{% url 'project:show_all' %}" class="btn btn-primary">Continue Shopping</a>
{% endblock %}

project/templates/project/create_customer_form.html
{% extends 'project/base.html' %}

{% block content %}

<br><br><br>
    <form method="POST">
        {% csrf_token %}
        <!-- {{form}} very generic -->
         <!-- {{form.as_p}} as paragaphs -->

    <table>
        {{form.as_table}}

        {{user_creation_form.as_table}}
        <tr>
            <td></td>
            
            <td colspan="2">
                <button type="submit" name="submit" value="Create account">Create Account</button>
            </td>
        </tr>
    </table>

    

    </form>

    <form action="{% url 'project:show_all' %}">
        <button type="submit" name="Cancel" value="Cancel">Cancel</button>
    </form>


{% endblock %}

project/templates/project/create_item_form.html
{% extends 'project/base.html' %}

{% block content %}
    <br><br><br>
    <h2>Create Item</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <table>
            {{ form.as_table }}  <!-- This will display the fields for the item -->
            
            <!-- File input for image uploads -->
            <tr>
                <td><h6>Choose images to upload:</h6></td>
                <td><input type="file" name="images" multiple></td>
            </tr>
        </table>
        
        <div style="text-align: center;">
            <button type="submit">Create Item</button>
        </div>
    </form>

    <form action="{% url 'project:show_self' %}">
        <button type="submit">
            Cancel
        </button>
    </form>


    
{% endblock %}

project/templates/project/item_detail.html
{% extends 'project/base.html' %}

{% block content %}

<h1>You are currently looking at:</h1>
    <div style="text-align: center;">
        <h1>{{item.title }}</h1>
        
        <div style="display: flex; justify-content: center; flex-wrap: wrap; gap: 10px;">
            {% for img in item.get_images %}
                    <img src="{{ img.image.url }}" alt="Item image" style="height: 250px;" />
                {% endfor %}

        </div>

        <p>Description: {{item.description}}</p>
        
        <p>1 unit of item for: ${{item.price}}</p>
        <p>Left on stock: {{item.quantity_left}}</p>
        <p>Item was updated on {{item.date}}</p>
        <p>Seller: {{item.customer}}</p>
        
<a href="{% url 'project:show_user' item.customer.pk %}">View Seller Profile</a><br><br><br>


{% if request.user.is_authenticated %}

        <form action="{% url 'project:chat_detail' item.customer.pk %}" method="get"  style="display: inline;">
            <button type="submit">
                Message Seller
            </button>
        </form>
        
        {% if item.quantity_left > 0 %}
        <form method="POST" action="{% url 'project:add_to_cart' item.pk %}" style="display: inline;">
            {% csrf_token %}
            <button type="submit">
                {% if item in request.user.cart_items.all %}
                    Add one more to cart
                {% else %}
                    Add to cart
                {% endif %}
            </button>
        </form>
        {% endif %}
    {% else %}
        <!-- Redirect unlogged users to login page with item ID in the URL -->
        <a href="{% url 'project:login' %}?next={% url 'project:add_to_cart' item.pk %}">
            <button type="button">Login to Add to Cart</button>
        </a>
    {% endif %}

    </div>
    



{% endblock %}

project/templates/project/notifications.html
{% extends 'project/base.html' %}

{% block content %}
<h1>Notifications</h1>

<form method="get" action="{% url 'project:notification' %}">
    <div>
        <label for="start_date">Start Date:</label>
        <input type="date" id="start_date" name="start_date" value="{{ request.GET.start_date|default_if_none:'' }}">
    </div>
    <div>
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" name="end_date" value="{{ request.GET.end_date|default_if_none:'' }}">
    </div>
    <div>
        <label for="sort_by">Sort By:</label>
        <select id="sort_by" name="sort_by">
            <option value="" {% if not request.GET.sort_by %}selected{% endif %}>Default(Latest First)</option>
            <option value="date_asc" {% if request.GET.sort_by == 'date_asc' %}selected{% endif %}>Earliest First</option>
            <option value="date_desc" {% if request.GET.sort_by == 'date_desc' %}selected{% endif %}>Latest First</option>
        </select>
    </div>
    <button type="submit">Filter</button>
</form>


{% if notifications %}
    <ul style="list-style: none; padding: 0; text-align: left;">
        {% for notification in notifications %}
            <li style="margin-bottom: 20px; border-bottom: 1px solid #ccc; padding-bottom: 10px;">
                <p style="margin: 0;">{{ notification.message }}</p>
                <small style="color: gray;">{{ notification.created_at }}</small>
                <br>
                {% if notification.is_read == False %}
                <form action="{% url 'project:mark_notification_read' notification.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Mark as Read</button>
                </form>
                {% endif %}
                <a href="{% url 'project:order_detail' notification.order.pk %}" style="color: blue; text-decoration: underline;">View Order Details</a>
            </li>
        {% endfor %}
    </ul>

    {% for item in items %}
    <!-- Your item display logic here -->
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        <span class="step-links">
            {% if page_obj.has_previous %}
                <form action="" method="get" style="display:inline;">
                    <input type="hidden" name="page" value="1">
                    <input type="hidden" name="start_date" value="{{ request.GET.start_date }}">
                    <input type="hidden" name="end_date" value="{{ request.GET.end_date }}">
                    <input type="hidden" name="sort_by" value="{{ request.GET.sort_by }}">
                    <button type="submit">&laquo; First</button>
                </form>
                <form action="" method="get" style="display:inline;">
                    <input type="hidden" name="page" value="{{ page_obj.previous_page_number }}">
                    <input type="hidden" name="start_date" value="{{ request.GET.start_date }}">
                    <input type="hidden" name="end_date" value="{{ request.GET.end_date }}">
                    <input type="hidden" name="sort_by" value="{{ request.GET.sort_by }}">
                    <button type="submit">Previous</button>
                </form>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <form action="" method="get" style="display:inline;">
                    <input type="hidden" name="page" value="{{ page_obj.next_page_number }}">
                    <input type="hidden" name="start_date" value="{{ request.GET.start_date }}">
                    <input type="hidden" name="end_date" value="{{ request.GET.end_date }}">
                    <input type="hidden" name="sort_by" value="{{ request.GET.sort_by }}">
                    <button type="submit">Next</button>
                </form>
                <form action="" method="get" style="display:inline;">
                    <input type="hidden" name="page" value="{{ page_obj.paginator.num_pages }}">
                    <input type="hidden" name="start_date" value="{{ request.GET.start_date }}">
                    <input type="hidden" name="end_date" value="{{ request.GET.end_date }}">
                    <input type="hidden" name="sort_by" value="{{ request.GET.sort_by }}">
                    <button type="submit">Last &raquo;</button>
                </form>
            {% endif %}
        </span>

        <form method="get" action="" class="page-number-form">
            <label for="page_number">Go to page:</label>
            <input type="number" name="page" id="page_number" min="1" max="{{ page_obj.paginator.num_pages }}" value="{{ page_obj.number }}">
            <input type="hidden" name="start_date" value="{{ request.GET.start_date }}">
            <input type="hidden" name="end_date" value="{{ request.GET.end_date }}">
            <input type="hidden" name="sort_by" value="{{ request.GET.sort_by }}">
            <button type="submit">Go</button>
        </form>
    {% endif %}
</div>
{% else %}
    <p>You have no notifications.</p>
{% endif %}
{% endblock %}

project/templates/project/order_detail.html
{% extends 'project/base.html' %}

{% block content %}

<h1>Order Details</h1>




<p>Customer: {{ order.customer.first_name }} {{ order.customer.last_name }}</p>
<p>Order Date: {{ order.date }}</p>
<p>Item: {{ order.item.title }}</p>
<p>Quantity: {{ order.quantity }}</p>
<p>Total Price: ${{ order.get_total_price }}</p>

<form action="{% url 'project:show_user' order.customer.pk %}">
    <button type="submit">
        To {{ order.customer.first_name }}'s personal page
    </button>
</form>

{% endblock %}

project/templates/project/show_user.html
{% extends 'project/base.html' %}

{% block content %}

<h1>{{ customer.first_name }} {{ customer.last_name }}</h1>


<h4>To update personal information, hit:</h4>
<form action="{% url 'project:update_account' %}">
    <button type="submit">
        Update Info
    </button>
</form>

<h4>To sell an item, hit:</h4>
<form action="{% url 'project:create_item' %}">
    <button type="submit">
        Sell an item
    </button>
</form>

<div>
    {% if customer.image_self %}
        <img src="{{ customer.image_self.url }}" alt="{{ customer.first_name }}'s Profile Picture">
    {% else %}
        <h4>No profile image available</h4>
    {% endif %}

    <p>Address: {{ customer.address }}</p>
    <p>Email: {{ customer.email_address }}</p>
    <p>Phone: {{ customer.phone_number }}</p>
</div>


<h2>Item(s) for Sale</h2>
<div>
    {% if items %}
        {% for c in items %}
            {% if c.get_first_image %}
                <a href="{% url 'project:show_detail' c.pk %}">
                    <img src="{{ c.get_first_image.image.url }}" alt="First Image">
                </a>
            {% endif %}
            <a href="{% url 'project:show_detail' c.pk %}" style="text-decoration: none; color: inherit;"><p>{{ c.title }}</p></a>

            <form action="{% url 'project:update_item' c.pk %}">
                <button type="submit">
                    Update {{ c.title }}
                </button>
            </form>

            <form action="{% url 'project:delete_item' c.pk %}" method="get">
                {% csrf_token %}
                <button type="submit">
                    Delete {{ c.title }}
                </button>
            </form>

        {% endfor %}
    {% else %}
        <p>No items for sale by {{ customer.first_name }}.</p>
    {% endif %}
</div>
{% endblock %}