blog/urls.py
## hw/urls.py

from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views

app_name="blog"

#list of urls to have
urlpatterns = [
    path(r'', views.RandomArticleView.as_view(), name='random'), # generic class-based view
    path(r'show_all', views.ShowAllView.as_view(), name='show_all'),
    path(r'article/<int:pk>', views.ArticleView.as_view(), name='article'),
    path(r'article/<int:pk>/create_comment', views.CreateCommentView.as_view(), name='create_comment'),
    path(r'create_article', views.CreateArticleView.as_view(), name='create_article'),
    #for authentication
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:show_all'), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),

]

cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include("hw.urls")),
    path('quotes/', include("quotes.urls")),
    path('formdata/', include("formdata.urls")),
    path('restaurant/', include("restaurant.urls")),
    path('blog/', include("blog.urls")),
    path('mini_fb/', include("mini_fb.urls")),
    path('marathon_analytics/', include("marathon_analytics.urls")),
    path('voter_analytics/', include("voter_analytics.urls")),
    path('project/', include("project.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hw/urls.py
## hw/urls.py

from django.urls import path
from django.conf import settings
from . import views

#list of urls to have
urlpatterns = [
    path(r'', views.home, name="home"),#name is same as the name of views
    path(r'about', views.about, name="about"),
    #must have the r before ''
    #path(url, view, name)
    
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
#deinfe data models

# Create your models here.

class Article(models.Model):
    #attributes:
    user = models.ForeignKey(User, on_delete=models.CASCADE) # new added user

    title = models.TextField(blank=False)
    author = models.TextField(blank=False)
    text = models.TextField(blank=False)
    published = models.DateTimeField(auto_now=True)
    ## image_url = models.URLField(blank=True) ##image field 
    image_fil = models.ImageField(blank=True)

    def __str__(self):
        return f"{self.title} by {self.author}"

    def get_comments(self):
        '''get all the comments related to this article'''
        comments = Comment.objects.filter(article=self)
        return comments
    
    def get_absolute_url(self):
        "returning url to view one instance of object"
        #pk = self.pk primary key of this object
        return reverse('blog:article', kwargs={'pk': self.pk})

        
class Comment(models.Model):
    'comment of articles'

    article = models.ForeignKey("Article", on_delete = models.CASCADE)
    author = models.TextField(blank=False)
    text = models.TextField(blank=False)
    published = models.DateTimeField(auto_now=True)

    def __str__(self):
        'return a string representation of object'
        return f'{self.text}'

    

    

blog/forms.py
from django import forms
from .models import Comment, Article

class CreateCommentForm(forms.ModelForm):
    '''forms for adding another comment'''

    class Meta:
        model = Comment
        fields = ['author', 'text'] #fields to include in the form


class CreateArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['author', 'title', 'text', 'image_fil']

blog/views.py
from django.shortcuts import render, redirect
from .models import Article

from django.views.generic import ListView, DetailView, CreateView
from .forms import *

from typing import Any
from django.urls import reverse

import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login



class ShowAllView(ListView):
    '''Create a subclass of ListView to display all blog articles.'''
    model = Article # retrieve objects of type Article from the database
    template_name = 'blog/show_all.html'
    context_object_name = 'articles'  ##read the object from databse(entirely!, all attributes)

    def dispatch(self, *args, **kwargs):
        print(f"self.request.user = {self.request.user}")
        return super().dispatch(*args, **kwargs)


class RandomArticleView(DetailView):
    "show article selected at random"
    model= Article
    template_name = 'blog/article.html'
    context_object_name = 'article'

    def get_object(self):
        '''return instance of article'''
        all_articles = Article.objects.all()

        return random.choice(all_articles)


class ArticleView(DetailView):
    "show article selected at random"
    model= Article
    template_name = 'blog/article.html'
    context_object_name = 'article'

    
class CreateCommentView(CreateView):
    '''A view to create comments on article
        on get: send back the for for dispay
        on post: rewad/process the form and save it to the DB
    '''

    form_class = CreateCommentForm
    template_name = "blog/create_comment_form.html"

    def get_context_data(self, **kwargs:Any) -> dict[str, Any]:

        #get the context data
        context = super().get_context_data(**kwargs)
        article = Article.objects.get(pk=self.kwargs['pk'])
        context['article'] = article
        return context

    def get_success_url(self) -> str:
        article = Article.objects.get(pk=self.kwargs['pk'])
        return reverse('blog:article', kwargs=self.kwargs)

    def form_valid(self, form):
        ###self.kwargs shows the pk, form.cleane_data shows the fields with its argument
        article = Article.objects.get(pk=self.kwargs['pk'])

        #attach the article to the instance of cmoment
        form.instance.article = article

        return super().form_valid(form)
        

class CreateArticleView(LoginRequiredMixin, CreateView):
    form_class = CreateArticleForm
    template_name = "blog/create_article_form.html"

    def get_login_url(self) -> str:
        return reverse('blog:login')

    def form_valid(self, form):
        #print(f'CreateArticleView.form_valid: form.cleaned_data = {form.cleaned_data}')
        user = self.request.user
        form.instance.user = user

        return super().form_valid(form)
    
class RegistrationView(CreateView):
    template_name='blog/register.html'
    form_class = UserCreationForm

    def dispatch(self, *args, **kwargs):

        #let superclass handle GET and we handle POST

        if self.request.POST:
            form = UserCreationForm(self.request.POST) #reconstruct the form
            if not form.is_valid(): #if something cause error(ex: password not match)
                return super().dispatch(*args, **kwargs)
            

            user = form.save() #save it to the DB
            login(self.request,user) #lgoin the user
        
            return redirect(reverse('blog:show_all'))

        return super().dispatch(*args, **kwargs)

blog/templates/blog/article.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>{{article.title}}</h1>

<main class="grid-container">

        <article> <!-- was div before -->
            <h2>{{article.title}}</h2>
            <h3>{{article.author}} at {{article.published}}</h3>
            <!-- <img src="{{article.image_url}}"> -->
            <img src="{{article.image_fil.url}}">

            <p>
                {{article.text}}
            </p>
        </article>

        <div>
            <h2>Comments</h2>
            <h3><a href="{% url 'blog:create_comment' article.pk %}">Create a comment</a></h3>
            {% if article.get_comments %}
                {% for c in article.get_comments %}
            
                    <strong>by {{c.author}} and {{c.published}} </strong>
                    <p>
                      {{c.text}}
                 </p>
                 {% endfor %}
              
             {% else %}
                <p>No comments</p>    
            
            {% endif %}

        </div>


</main>

{% endblock %}

blog/templates/blog/base.html
<!-- templates/base.html -->
<!-- blog/templates/blog/base.html -->



{% load static %}

<html>
    <head>
        <title>Blog</title>
        <link rel="stylesheet" href="{% static 'styles_blog.css' %}">
    </head>
    <body>

        <nav>
            <a href="{% url 'blog:random' %}">Random</a>  <!-- we can do href="/hw/", but this is more generic -->
            <a href="{% url 'blog:show_all' %}">Show all</a>
            


         {% if request.user.is_authenticated %}
            <a href="{% url 'blog:create_article' %}">Create Article </a>
            <form method="POST" action="{% url 'blog:logout' %}">
                {% csrf_token %}
                <input type="submit" value="Logout">
            </form>
          {% else %}
          
          
            <a href="{% url 'blog:login' %}">Login </a>
            
            {% endif %}
  
          </nav>
          {% if request.user.is_authenticated %}
          <p>logged in: {{request.user}}</p>
          {% else %}
          <p>not logged in</p>
          {% endif %}
        <header>
            <h1>Blog</h1>
        </header>
    
    {% block content %}

    {% endblock %}    
  
    </body>
</html>

blog/templates/blog/create_article_form.html
{% extends 'blog/base.html' %}

{% block content %}



    <h2>Create a Article</h2>

    <form method="POST" enctype="multipart/form-data"> <!-- enctype="multipart/form-data" must include for file submisison -->
        {% csrf_token %}
        <!-- {{form}} very generic -->
         <!-- {{form.as_p}} as paragaphs -->

    <table>
        {{form.as_table}}
    </table>

   

    <input type="submit" name="submit" value="Create article">

    
    </form>

    <form action="{% url 'blog:show_all' %}">
        <input type="submit" name="Cancel" value="Cancel">
    </form>
        

{% endblock %}

blog/templates/blog/create_comment_form.html
{% extends 'blog/base.html' %}

{% block content %}



    <h2>Create a comment {{article.title}}</h2>

    <form method="POST">
        {% csrf_token %}
        <!-- {{form}} very generic -->
         <!-- {{form.as_p}} as paragaphs -->

    <table>
        {{form.as_table}}
    </table>

   

    <input type="submit" name="submit" value="Create comment">

    
    </form>

    <form action="{% url 'blog:article' article.pk %}">
        <input type="submit" name="Cancel" value="Cancel">
    </form>
        

{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}

<h3>login</h3>

<form method="POST" action="{% url 'blog:login' %}">
    {% csrf_token %}

    {{form}}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% else %}
    <input type="hidden" name="next" value="{% url 'blog:show_all' %}">
    {% endif %}
    <input type="submit" value="Login">
</form>

<a href="{% url 'blog:register' %}">Register here</a>

{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block content %}

<h3>register</h3>

<form method="POST" action="{% url 'blog:register' %}">
    {% csrf_token %}

    {{form}}
    <input type="submit" name="register" value="register">
</form>


{% endblock %}

blog/templates/blog/show_all.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Showing all articles</h1>

<main class="grid-container">
    {% for a in articles %}
        <a href="{% url 'blog:article' a.pk %}">
            <img src="{{a.image_fil.url}}">
        </a>
        <article> <!-- was div before -->
            <h2> <a href="{% url 'blog:article' a.pk %}">{{a.title}}</a></h2>

            <h3>{{a.author}} at {{a.published}}</h3>
           
            <p>
                {{a.text}}
            </p>
        </article>
    {% endfor %}


</main>

{% endblock %}