cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include("hw.urls")),
    path('quotes/', include("quotes.urls")),
    path('formdata/', include("formdata.urls")),
    path('restaurant/', include("restaurant.urls")),
    path('blog/', include("blog.urls")),
    path('mini_fb/', include("mini_fb.urls")),
    path('marathon_analytics/', include("marathon_analytics.urls")),
    path('voter_analytics/', include("voter_analytics.urls")),
    path('project/', include("project.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hw/urls.py
## hw/urls.py

from django.urls import path
from django.conf import settings
from . import views

#list of urls to have
urlpatterns = [
    path(r'', views.home, name="home"),#name is same as the name of views
    path(r'about', views.about, name="about"),
    #must have the r before ''
    #path(url, view, name)
    
]

marathon_analytics/urls.py
from django.urls import path
#from django.conf import settings
from . import views
#from django.contrib.auth import views as auth_views

app_name='marathon_analytics'

urlpatterns = [
    path(r'', views.ResultsListView.as_view(), name='home'), # generic class-based view
    path(r'results', views.ResultsListView.as_view(), name='results'),
    path(r'result/<int:pk>', views.ResultDetailView.as_view(), name='result_detail'),
]

marathon_analytics/models.py
from django.db import models

# Create your models here.

class Result(models.Model):
    '''
    Store/represent the data from one runner at the Chicago Marathon 2023.
    BIB,First Name,Last Name,CTZ,City,State,Gender,Division,
    Place Overall,Place Gender,Place Division,Start TOD,Finish TOD,Finish,HALF1,HALF2
    '''
    # identification
    bib = models.IntegerField()
    first_name = models.TextField()
    last_name = models.TextField()
    ctz = models.TextField()
    city = models.TextField()
    state = models.TextField()
    # gender/division
    gender = models.CharField(max_length=6)
    division = models.CharField(max_length=6)
    # result place
    place_overall = models.IntegerField()
    place_gender = models.IntegerField()
    place_division = models.IntegerField()
    # timing-related
    start_time_of_day = models.TimeField()
    finish_time_of_day = models.TimeField()
    time_finish = models.TimeField()
    time_half1 = models.TimeField()
    time_half2 = models.TimeField()

    def __str__(self):
        '''Return a string representation of this model instance.'''
        return f'{self.first_name} {self.last_name} ({self.city}, {self.state}), {self.time_finish}'
    
    def get_runner_passed(self):
        start_first = Result.objects.filter(start_time_of_day__lt = self.start_time_of_day)
        passed = start_first.filter(finish_time_of_day__gt=self.finish_time_of_day)
        return len(passed)
    
    def get_runner_passed_by(self):
        start_late = Result.objects.filter(start_time_of_day__gt = self.start_time_of_day)
        passed = start_late.filter(finish_time_of_day__lt=self.finish_time_of_day)
        return len(passed)

def load_data():
    '''loading data records from csv files'''

    '''delete all records if needed'''

    Result.objects.all().delete() #if we want to strat with an EMPTY DB
    filename = '../2023_chicago_results.csv'
    f = open(filename)
    headers = f.readline() #discard first line which includes the headers

    #line = f.readline().strip() #strip remove the space at the end
   
    #print(line)
    for line in f:
        try:
            fields = line.split(',') #split by comma 
            result = Result(bib=fields[0],
                        first_name=fields[1],
                        last_name=fields[2],
                        ctz = fields[3],
                        city = fields[4],
                        state = fields[5],
                        
                        gender = fields[6],
                        division = fields[7],
                        place_overall = fields[8],
                        place_gender = fields[9],
                        place_division = fields[10],
                    
                        start_time_of_day = fields[11],
                        finish_time_of_day = fields[12],
                        time_finish = fields[13],
                        time_half1 = fields[14],
                        time_half2 = fields[15],
                    )
            print(f'Created result: {result}')
            result.save() #saving to the DB
        except:
            print("exception occured")
            

marathon_analytics/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Result
from django.db.models.query import QuerySet
import plotly
import plotly.graph_objs as go


# Create your views here.

class ResultsListView(ListView):
    '''view to display list of marathon results'''
    template_name = 'marathon_analytics/results.html'
    model = Result
    context_object_name = "results" #name to be used in html file
    paginate_by = 50 #limits number to show on page

    def get_queryset(self):
        qs = super().get_queryset()

        if 'city' in self.request.GET:
            city = self.request.GET['city']
            if city: #if blank
                qs = Result.objects.filter(city__icontains=city) 

        return qs

class ResultDetailView(DetailView):

    template_name = 'marathon_analytics/result_detail.html'
    model = Result
    context_object_name = 'r'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)

        r = context['r']
        x = [f'runners passed {r.first_name}',
             f'runners who passed {r.first_name}']
        
        y = [r.get_runner_passed(), r.get_runner_passed_by()]

        fig = go.Bar(x=x, y=y)
        graph_div = plotly.offline.plot({"data":[fig]}, auto_open=False, output_type = 'div'
                    )
        context['graph_div'] = graph_div

        #pie char for first half and second half
        x=['first half time', 'second half time']

        first_half_sec = r.time_half1.hour * 3600 + r.time_half1.minute * 60 + r.time_half1.second
        second_half_sec = r.time_half2.hour * 3600 + r.time_half2.minute * 60 + r.time_half2.second

        y=[first_half_sec, second_half_sec]

        fig = go.Pie(labels=x, values=y)
        pie_div = plotly.offline.plot({"data":[fig]}, auto_open=False, output_type = 'div'
                    )
        context['pie_div'] = pie_div

        return context

marathon_analytics/templates/marathon_analytics/base.html
{% load static %}
<html>
    <head>
        <title>Marathon Analytics</title>
        <link rel="stylesheet" href="{% static 'MA.css' %}">
    </head>
    <body>
        <header>
            <h1>Marathon Analytics</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'marathon_analytics:home' %}">Home</a></li>
                </ul>
            </nav>
        </header>
    
    {% block content %}
    {% endblock %}    
  
    </body>
</html>

marathon_analytics/templates/marathon_analytics/result_detail.html
<!-- templates/marathon_analytics/result_detail.html -->
{% extends 'marathon_analytics/base.html' %}
{% block content %}
<div class="container">
    <h1>Showing Result for {{r.first_name}} {{r.last_name}}</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Citizenship</th>
            <th>City, State</th>
            <th>Division</th>
            
            <th>Place Overall</th>
            <th>Place Gender</th>
            <th>Place Division</th>
            <th>First Half</th>
            <th>Second Half</th>
            <th>Finish Time</th>
        </tr>
        
        <tr>
            <td>{{r.first_name}} {{r.last_name}}</td>
            <td>{{r.ctz}}</td>
            <td>{{r.city}}, {{r.state}}</td>
            <td>{{r.gender.0}} {{r.division}}</td>
            <td>{{r.place_overall}}</td>
            <td>{{r.place_gender}}</td>
            <td>{{r.place_division}}</td>
            <td>{{r.time_half1|time:"H:i:s"}}</td>
            <td>{{r.time_half2|time:"H:i:s"}}</td>
            <td>{{r.time_finish|time:"H:i:s"}}</td>
        </tr>
    </table>

    <div class="row">
        <p>
            passed {{r.get_runner_passed}}
        </p>
        <p>
            passed by {{r.get_runner_passed_by}}
        </p>

    </div>

    <div class="row">
        {{graph_div|safe}}
    </div>

    <div class="row">
        {{pie_div|safe}}
    </div>
</div>

{% endblock %}

marathon_analytics/templates/marathon_analytics/results.html
<!-- templates/marathon_analytics/results.html -->
{% extends 'marathon_analytics/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% include 'marathon_analytics/search.html' %} <!-- import from another file -->
    </div>
    <h1>Results</h1>
    <div class="row">
        <table>
            <tr>
                <th>Place Overall</th>
                <th>Name</th>
                <th>Citizenship</th>
                <th>City, State</th>
                <th>Division</th>
                
                <th>First Half</th>
                <th>Second Half</th>
                <th>Finish Time</th>
            </tr>
    
            {% for r in results %}
            <tr>
                
                <td>
                    <a href="{% url 'marathon_analytics:result_detail' r.pk %}">
                        {{ r.place_overall }}
                    </a>
                </td>
                <td>{{r.first_name}} {{r.last_name}}</a>
                </td>
                <td>{{r.ctz}}</td>
                <td>{{r.city}}, {{r.state}}</td>
                <td>{{r.gender.0}} {{r.division}}</td>
                
                <td>{{r.time_half1|time:"H:i:s"}}</td>
                <td>{{r.time_half2|time:"H:i:s"}}</td>
                <td>{{r.time_finish|time:"H:i:s"}}</td>
             
            </tr>
            {% endfor %}
    
        </table>
        </div>
    </div>

    <div class="row">
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li>
                    <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
             
                </li>
            {% endif %}
                <li class="">
                    <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </li>
            {% if page_obj.has_next %}
                <li>
                    <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                </li>
            {% endif %}
            </ul>
        {% endif %}
    </div>
    
{% endblock %}

marathon_analytics/templates/marathon_analytics/search.html
<h3>Search Form</h3>

<form action="{% url 'marathon_analytics:results' %}">
<table>

    <tr>
        <th>City:</th>
        <td><input type="text" name="city"></td>
    </tr>
    
    <tr>
        <td></td>
        <td><input type="submit"></td> 
    </tr>

</table>
</form>