blog/urls.py
## hw/urls.py

from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views

app_name="blog"

#list of urls to have
urlpatterns = [
    path(r'', views.RandomArticleView.as_view(), name='random'), # generic class-based view
    path(r'show_all', views.ShowAllView.as_view(), name='show_all'),
    path(r'article/<int:pk>', views.ArticleView.as_view(), name='article'),
    path(r'article/<int:pk>/create_comment', views.CreateCommentView.as_view(), name='create_comment'),
    path(r'create_article', views.CreateArticleView.as_view(), name='create_article'),
    #for authentication
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:show_all'), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),

]

cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include("hw.urls")),
    path('quotes/', include("quotes.urls")),
    path('formdata/', include("formdata.urls")),
    path('restaurant/', include("restaurant.urls")),
    path('blog/', include("blog.urls")),
    path('mini_fb/', include("mini_fb.urls")),
    path('marathon_analytics/', include("marathon_analytics.urls")),
    path('voter_analytics/', include("voter_analytics.urls")),
    path('project/', include("project.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hw/urls.py
## hw/urls.py

from django.urls import path
from django.conf import settings
from . import views

#list of urls to have
urlpatterns = [
    path(r'', views.home, name="home"),#name is same as the name of views
    path(r'about', views.about, name="about"),
    #must have the r before ''
    #path(url, view, name)
    
]

mini_fb/urls.py
# File: urls.py
# Author: Shuaiqi Huang (shuang20@bu.edu) 11/1/2024
# Description: url patterns for different pages

from django.urls import path
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_views

app_name='mini_fb'

urlpatterns = [
    path(r'', views.ShowAllProfilesView.as_view(), name='show_all'), # generic class-based view
    path(r'profile/<int:pk>', views.ShowProfilePageView.as_view(), name='show_profile'), #profile detail view
    path(r'create_profile', views.CreateProfileView.as_view(), name='create_profile'), #forms to create a profile
    path(r'status/create_status', views.CreateStatusMessageView.as_view(), name='URL_create_status'), #creating a message
    path(r'profile/update', views.UpdateProfileView.as_view(), name='update_profile'), #updating profile
    path(r'status/<int:pk>/delete', views.DeleteStatusMessageView.as_view(), name='delete_message'), #deleting statue message
    path(r'profile/<int:pk>/update_message', views.UpdateStatusMessageView.as_view(), name='update_message'), #updating status message
    path(r'profile/add_friend/<int:other_pk>', views.CreateFriendView.as_view(), name='add_friend'), #creating friend view
    path(r'profile/friend_suggestions', views.ShowFriendSuggestionsView.as_view(), name='friend_suggestions'), #view friend suggestions
    path(r'profile/news_feed', views.ShowNewsFeedView.as_view(), name='news_feed'), #view news feed related to that person

    path('login/', auth_views.LoginView.as_view(template_name='mini_fb/login.html'), name='login'), #logging in
    path('logout/', auth_views.LogoutView.as_view(template_name='mini_fb/logged_out.html'), name='logout'), #logging out 
]

mini_fb/forms.py
# File: forms.py
# Author: Shuaiqi Huang (shuang20@bu.edu) 10/19/2024
# Description: forms to process a new profile and adding status message

from django import forms
from .models import Profile, StatusMessage


class CreateProfileForm(forms.ModelForm):
    '''forms for adding another new profile'''

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'city', 'email_address', 'image_url'] #fields to include in the form

class CreateStatusMessageForm(forms.ModelForm):
    '''forms for add a status message for a profile'''
    class Meta:
        model = StatusMessage
        fields = ['message'] #fields to include in the form

class UpdateProfileForm(forms.ModelForm):
    '''forms to update an existing profile'''
    class Meta:
        model = Profile
        fields = ['city', 'email_address', 'image_url'] #fields to include in the form

class UpdateStatusMessageForm(forms.ModelForm):
    '''form to update an existing status message'''
    class Meta:
        model = StatusMessage
        fields = ['message'] #fields to include in the form, timestamp not needed as automatically filled

mini_fb/views.py
# File: views.py
# Author: Shuaiqi Huang (shuang20@bu.edu) 11/1/2024
# Description: presentation to the user: showall profiles and detail profiles
#creating profile and status message, and redirecting/rendering

from django.shortcuts import render
from .models import Profile, StatusMessage, Image
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, TemplateView

from .forms import *

from typing import Any
from django.urls import reverse

from django.http import HttpResponseRedirect

import random


from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import redirect


class ShowAllProfilesView(ListView):
    '''Create a subclass of ListView to display all profile.'''
    model = Profile # retrieve objects of type Profile from the database
    template_name = 'mini_fb/show_all_profiles.html'
    context_object_name = 'profiles'  ##read the object from databse(entirely!, all attributes)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_profile = None

        if self.request.user.is_authenticated:
            # Attempt to retrieve the profile associated with the logged-in user
            user_profile = Profile.objects.filter(user=self.request.user).first()
        
        context['user_profile'] = user_profile
        return context    
    

class ShowProfilePageView(DetailView):
    '''show a specific profile from the databse'''
    model = Profile
    template_name = 'mini_fb/show_profile.html'
    context_object_name = 'profile'



class CreateProfileView(CreateView):
    '''A view to create message on profile
        on get: send back the for for dispay
        on post: read/process the form and save it to the DB
    '''

    form_class = CreateProfileForm #form that forms.py has
    template_name = "mini_fb/create_profile_form.html"

    def get_context_data(self, **kwargs):
        #get context data for creating new user
        context = super().get_context_data(**kwargs)
        # Add UserCreationForm to the context
        if not self.request.user.is_authenticated:
            context['user_creation_form'] = UserCreationForm()
        return context
   
    
    def dispatch(self, request, *args, **kwargs):
        #handle logic when trying to create new profile
        if request.user.is_authenticated:
            # If user has a profile, redirect them to the main page
            if Profile.objects.filter(user=request.user).exists():
                return HttpResponseRedirect(reverse('mini_fb:show_all'))
   
        return super().dispatch(request, *args, **kwargs)
    
    
    
    def form_valid(self, form):
        #  Reconstruct UserCreationForm from POST data
        if self.request.POST:
            user_creation_form = UserCreationForm(self.request.POST)
        
        # Check if UserCreationForm is valid before proceeding
        if user_creation_form.is_valid():
           #Save the new user and get the created User instance
            new_user = user_creation_form.save()
            
            #Attach the new user to the profile instance and log then in
            form.instance.user = new_user
            login(self.request, new_user)
            
            # Delegate the rest to the super class’ form_valid method
            return super().form_valid(form)
        else:
          #invalid form
            return self.form_invalid(form)



class CreateStatusMessageView(LoginRequiredMixin, CreateView):
    '''A view to create comments on article
        on get: send back the for for dispay
        on post: rewad/process the form and save it to the DB
    '''

    form_class = CreateStatusMessageForm #form that forms.py has
    template_name = "mini_fb/create_status_form.html"

    def get_context_data(self, **kwargs:Any) -> dict[str, Any]:

        #get the context data, which profile are we accessing?
        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        context['profile'] = profile
        return context
    
    def get_login_url(self) -> str:
        return reverse('mini_fb:login')
    
    def get_object(self):
        #get profile related to self
        return Profile.objects.get(user=self.request.user)

    def dispatch(self, request, *args, **kwargs):
        #logichandling when trying to create new message: must be correct user
        if not request.user.is_authenticated:
            return redirect('mini_fb:login')
        # Get the message to be deleted
        profile = self.get_object()
        # Only allow deletion if the user owns the message
        if profile.user != request.user:
            profile_url = reverse('mini_fb:show_profile', args=[profile.pk])
            return HttpResponseRedirect(profile_url)
        return super().dispatch(request, *args, **kwargs)    

    

    def get_success_url(self) -> str:
        '''once created message, redirect back to the profile page, showing the message along with profile info'''
        #updated as we changed structure, pk needs to be obtained in anotehr way
        return reverse('mini_fb:show_profile', kwargs={'pk': self.get_object().pk})


    def form_valid(self, form):
        ###self.kwargs shows the pk, form.cleane_data shows the fields with its argument

        profile = self.get_object()

        #attach the article to the instance of cmoment
        form.instance.profile = profile

        sm = form.save()

        # Read the files from the multi-part form data
        files = self.request.FILES.getlist('files')

        for file in files:
        # Create a new Image object
            image = Image(statusMessage=sm, image_url=file)
        # Save the Image object to the database
            image.save()
        return super().form_valid(form)
        

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    '''updating profile view'''
    form_class = UpdateProfileForm #form that forms.py has
    template_name = "mini_fb/update_profile_form.html" #html page which tells where to go
    model = Profile

    def get_login_url(self) -> str:
        return reverse('mini_fb:login')
    
    def get_object(self, queryset=None):
        #get profile of self
        return Profile.objects.get(user=self.request.user)
    
    def dispatch(self, request, *args, **kwargs):
        # Get the message to be deleted
        if not request.user.is_authenticated:
            return redirect('mini_fb:login')
        profile = self.get_object()
        # Only allow deletion if the user owns the message
        
        if profile.user != request.user:
            profile_url = reverse('mini_fb:show_profile', args=[profile.pk])
            return HttpResponseRedirect(profile_url)
        return super().dispatch(request, *args, **kwargs)


class  DeleteStatusMessageView(LoginRequiredMixin, DeleteView):
    '''deleting status message view, used for deletion'''
    template_name = "mini_fb/delete_status_form.html" #html page which tells where to go
    model = StatusMessage
    context_object_name = 'status_message' #self define a message name

    def get_success_url(self):
        '''Return a the URL to which we should be directed after the deletion(previous page)'''
        # get the pk for this comment
        pk = self.kwargs.get('pk')
        message = StatusMessage.objects.filter(pk=pk).first() # get one object from QuerySet
        
        # find the article to which this message is related by FK
        profile = message.profile
        # reverse to show the page
        return reverse('mini_fb:show_profile', kwargs={'pk':profile.pk})
    
    def get_login_url(self) -> str:
        return reverse('mini_fb:login')
    
    def dispatch(self, request, *args, **kwargs):
        #see if user is logged in or not, make sure it's the same user
        if not request.user.is_authenticated:
            return redirect('mini_fb:login')
        # Get the message to be deleted
        message = self.get_object()
        # Only allow deletion if the user owns the message
        if message.profile.user != request.user:
            profile = message.profile
            profile_url = reverse('mini_fb:show_profile', args=[profile.pk])
            return HttpResponseRedirect(profile_url)
        return super().dispatch(request, *args, **kwargs)

class UpdateStatusMessageView(LoginRequiredMixin, UpdateView):
    '''updating status message '''
    form_class= UpdateStatusMessageForm #form that accomplish this action
    template_name="mini_fb/update_status_message_form.html"  #html page which tells where to go
    model = StatusMessage
    context_object_name='status_message' #self define the name to use in html file

    def get_success_url(self):
        '''Return a the URL to which we should be directed after the update'''
        status_message = self.get_object()  # Get the current StatusMessage
        #return to the previous page
        return reverse('mini_fb:show_profile', kwargs={'pk': status_message.profile.pk})
    
    def get_login_url(self) -> str:
        return reverse('mini_fb:login')
    
    def dispatch(self, request, *args, **kwargs):
        #make sure it's the right owner of message
        if not request.user.is_authenticated:
            return redirect('mini_fb:login')
        # Get the message to be deleted
        message = self.get_object()
        # Only allow deletion if the user owns the message
        if message.profile.user != request.user:
            profile = message.profile
            profile_url = reverse('mini_fb:show_profile', args=[profile.pk])
            return HttpResponseRedirect(profile_url)
        return super().dispatch(request, *args, **kwargs)


class CreateFriendView(LoginRequiredMixin, View):
    '''newly defined create friend view, no model/template needed '''

mini_fb/templates/mini_fb/base.html
<!-- same file name as the views name 
 base page from which all other pages will inherit-->


 {% load static %}

 <html>
     <head>
         <link rel = "stylesheet" href = "{% static 'styles_mini_fb.css' %}"> 
         <title>
            mini facebook
         </title>
     </head>
 
 
     <body>
         <nav>
          <!-- <a href="{% url 'quote' %}">Quote</a> <br> -->  <!-- we can do href="/hw/", but this is more generic -->
         
          <a href="{% url 'mini_fb:show_all' %}">All Profiles</a><br>
          
          


          {% if request.user.is_authenticated %}
          
          {% if user_profile %}
          <li><a href="{% url 'mini_fb:show_profile' user_profile.pk %}">My Profile</a></li>
          <li><a href="{% url 'mini_fb:news_feed' %}">News feed</a></li>
        {% endif %}


            <form method="POST" action="{% url 'mini_fb:logout' %}">
                {% csrf_token %}
                <input type="submit" value="Logout">
            </form>
          {% else %}
            <a href="{% url 'mini_fb:create_profile' %}">Create Profile </a><br>
            <a href="{% url 'mini_fb:login' %}">Login </a>
            
            {% endif %}

          </nav>
          {% if request.user.is_authenticated %}
          <p>logged in: {{request.user}}</p>
          {% else %}
          <p>not logged in</p>
          {% endif %}
         </nav>
 
        {% block content %}
        <!-- put stuff/content here-->
        {% endblock %}
     </body>
 </html>

mini_fb/templates/mini_fb/create_profile_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}




    <form method="POST">
        {% csrf_token %}
        <!-- {{form}} very generic -->
         <!-- {{form.as_p}} as paragaphs -->

    <table>
        {{form.as_table}}

        {{user_creation_form.as_table}}
    </table>

   

    <input type="submit" name="submit" value="Create profile">

    
    </form>

    <form action="{% url 'mini_fb:show_all' %}">
        <input type="submit" name="Cancel" value="Cancel">
    </form>


{% endblock %}

mini_fb/templates/mini_fb/create_status_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{form}} very generic -->
         <!-- {{form.as_p}} as paragaphs -->

    <table>
        {{form.as_table}}
    </table>

    <h6>Choose some image to upload:</h6>
    <input type="file" name = "files" multiple /><br>

    <input type="submit" name="submit" value="Create Message">

    
    </form>

    <form action="{% url 'mini_fb:show_profile' profile.pk %}">
        <input type="submit" name="Cancel" value="Cancel">
    </form>

  

        

{% endblock %}

mini_fb/templates/mini_fb/delete_status_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}


<h3>Deleting message</h3>
{{status_message}}

    <form method="POST">
        {% csrf_token %}

    <input type="submit" name="yes" value="yes">

    
    </form>

    <form method="GET" action="{% url 'mini_fb:show_profile' status_message.profile.pk %}">
        {% csrf_token %}
        <input type="submit" name="no" value="no">
    </form>

        

{% endblock %}

mini_fb/templates/mini_fb/friend_suggestions.html
<!-- friend_suggestions.html -->
{% extends 'mini_fb/base.html' %}

{% block content %}

<h2>Friend Suggestions for {{ profile.first_name }} {{ profile.last_name }}</h2>

{% if friend_suggestions %}
    <ul>
        {% for suggestion in friend_suggestions %}
            <li>
                <a href="{% url 'mini_fb:show_profile' suggestion.pk %}">
                    {{ suggestion.first_name }} {{ suggestion.last_name }}
                </a>
                <a href="{% url 'mini_fb:add_friend' suggestion.pk %}">Add Friend</a>
                <img src="{{ suggestion.image_url }}" alt="{{ suggestion.first_name }}">
                <br><br><br>
                <!-- Link to add as a friend -->
                
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No friend suggestions available.</p>
{% endif %}

<a href="{% url 'mini_fb:show_profile' profile.pk %}">Back to Profile</a>

{% endblock %}

mini_fb/templates/mini_fb/logged_out.html
{% extends 'mini_fb/base.html' %}

{% block content %}

<h3>You have logged out</h3>


<a href="{% url 'mini_fb:show_all' %}">Main page</a><br><br><br>
<a href="{% url 'mini_fb:login' %}">Login again</a>



{% endblock %}

mini_fb/templates/mini_fb/login.html
{% extends 'mini_fb/base.html' %}

{% block content %}

<h3>login</h3>

<form method="POST" action="{% url 'mini_fb:login' %}">
    {% csrf_token %}

    {{form}}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% else %}
    <input type="hidden" name="next" value="{% url 'mini_fb:show_all' %}">
    {% endif %}
    <input type="submit" value="Login">
</form>



{% endblock %}

mini_fb/templates/mini_fb/news_feed.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>News Feed for {{ profile.first_name }} {{ profile.last_name }}</h2>

<!-- Link back to the profile page -->
<a href="{% url 'mini_fb:show_profile' profile.pk%}">Back to Profile</a>

<!-- Display each status message in the news feed -->
{% if news_feed %}
    {% for status in news_feed %}
        <div class="status-message">
            <!-- Display the profile picture of the person who wrote the status -->
            <img src="{{ status.profile.image_url }}" alt="{{ status.profile.first_name }}'s Profile Picture">
            <p><strong>{{ status.profile.first_name }} {{ status.profile.last_name }}</strong> posted:</p>
            <p>{{ status.message }}</p>
            <p><small>Posted at: {{ status.timestamp }}</small></p>
            <hr>
        </div>
    {% endfor %}
{% else %}
    <p>No status messages available in the news feed.</p>
{% endif %}


<a href="{% url 'mini_fb:show_profile' profile.pk %}">Back to Profile</a>


{% endblock %}

mini_fb/templates/mini_fb/show_all_profiles.html
{% extends 'mini_fb/base.html' %}

{% block content %}

<h1>Showing all profiles</h1>

<main class="grid-container">
    {% for a in profiles %}

        <profile> <!-- was div before -->
            <h2><a href="{% url 'mini_fb:show_profile' a.pk %}">Name: {{a.first_name}} {{a.last_name}}</a></h2>
            <h4>Email: {{a.email_address}}</h4>
            <h4>City: {{a.city}}</h4>
            
            <a href="{% url 'mini_fb:show_profile' a.pk %}">
            <img src="{{a.image_url}}">
            </a>
            <p>
                
            </p>
        </profile>
    {% endfor %}


    {% for a in articles %}
    <a href="{% url 'blog:article' a.pk %}">
        <img src="{{a.image_url}}">
    </a>
    <article> <!-- was div before -->
        <h2> <a href="{% url 'blog:article' a.pk %}">{{a.title}}</a></h2>

        <h3>{{a.author}} at {{a.published}}</h3>
       
        <p>
            {{a.text}}
        </p>
    </article>
{% endfor %}

</main>

{% endblock %}

mini_fb/templates/mini_fb/show_profile.html
{% extends 'mini_fb/base.html' %}

{% block content %}

<h3><a href="{% url 'mini_fb:update_profile'%}">Update Profile</a></h3>
<a href="{% url 'mini_fb:news_feed' %}">View News Feed</a>
<h2 style="text-align: center;">Showing detail of {{profile.first_name}} {{profile.last_name}}</h2>

<table style="margin: 0 auto;">
    <tr>
        <td colspan="2"><img src="{{profile.image_url}}"></td>
    </tr>

    <tr>
        <th>Name:</th>
        <td>{{profile.first_name}} {{profile.last_name}}</td>
    </tr>
    <tr>
        <th>City:</th>
        <td>{{profile.city}}</td>
    </tr>
    <tr>
        <th>Email:</th>
        <td>{{profile.email_address}}</td>
    </tr>
    
</table>


<div>
    <h2>Status Message</h2>
    <h3><a href="{% url 'mini_fb:URL_create_status' %}">Create a message</a></h3>
    
    {% if profile.get_status_messages %}
        {% for c in profile.get_status_messages %}
        <p>
              Message at {{c.timestamp}}: {{c.message}}
         </p>
         <a href="{% url 'mini_fb:delete_message' c.pk %}">Delete message</a>
         <a href="{% url 'mini_fb:update_message' c.pk %}">Update message</a>
            {% if c.get_images %}
                    <h4>Image(s) along with the message:</h4>
                        {% for img in c.get_images %}
                                <img src="{{ img.image_url.url }}" alt="Image for {{ c.message }}"><br>
                        {% endfor %}
                   
            {% endif %}
            <hr>
            
         
         {% endfor %}
      
     {% else %}
        <p>No status message</p>    
    
    {% endif %}

</div>

    <h2>Friends</h2>
    <a href="{% url 'mini_fb:friend_suggestions' %}">Friend Suggestions</a>
        {% if profile.get_friends %}
        {% for f in profile.get_friends %}
            {% if f.profile2 == profile %}
            
            <img src="{{ f.profile1.image_url }}" alt="{{ f.profile1.first_name }}">
            <p> <a href="{% url 'mini_fb:show_profile' f.profile1.pk %}">{{ f.profile1.first_name }} {{ f.profile1.last_name }}</a></p>
            {% else %}
            <a href="{% url 'mini_fb:show_profile' f.profile2.pk %}">
                <!-- Friend's profile picture and name -->
            </a>
            <img src="{{ f.profile2.image_url }}" alt="{{ f.profile2.first_name }}">
            <p><a href="{% url 'mini_fb:show_profile' f.profile2.pk %}">{{ f.profile2.first_name }} {{ f.profile2.last_name }}</a></p>
            
            {% endif %}
         {% endfor %}
        
        {% endif %}


{% endblock %}

mini_fb/templates/mini_fb/update_profile_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}


<h3>Update {{profile.first_name}} {{profile.last_name}}'s profile (your profile)</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
       
    <table>
        {{form.as_table}}
    </table>

   

    <input type="submit" name="update profile" value="Update profile">

    
    </form>

    <form action="{% url 'mini_fb:show_profile' profile.pk %}">
        <input type="submit" name="Cancel" value="Cancel">
    </form>

        

{% endblock %}

mini_fb/templates/mini_fb/update_status_message_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}


<h3>Update message</h3>

    <form method="POST">
        {% csrf_token %}
       
    <table>
        {{form.as_table}}
    </table>

   
    <input type="submit" name="update message" value="Update message">

    </form>

    <form action="{% url 'mini_fb:show_profile' status_message.profile.pk %}">
        <input type="submit" name="Cancel" value="Cancel">
    </form>

        

{% endblock %}